<template>
  <div class="scene-panel" :style="{height}">
    <div class="head"><b>{{ floorMode ? floorTitle : '设备场景总览' }}</b><span>{{ floorMode ? '楼层内部视角：摄像头 / 消防 / 门禁 / 环境点位' : '园区视角：点击楼栋下钻到楼层内部' }}</span></div>
    <div class="toolbar">
      <button @click="backPark">园区总览</button><button @click="view('fire')">消防视角</button><button @click="view('security')">安防视角</button><button @click="view('room')">设备房视角</button><button class="danger" @click="alarm">模拟告警</button>
    </div>
    <div ref="host" class="host"></div>
    <transition name="fade"><div v-if="loading" class="mask">{{ loadingText }}</div></transition>
    <div v-show="tip.show" class="tip" :class="{alarm:tip.alarm}" :style="{left:tip.x+'px',top:tip.y+'px'}"><h4>{{tip.title}}</h4><p>类型：{{tip.type}}</p><p>位置：{{tip.location}}</p><p>状态：<em>{{tip.status}}</em></p><small>{{tip.desc}}</small></div>
    <div class="side"><h4>{{ floorMode ? '楼层设备清单' : '园区重点对象' }}</h4><p v-for="i in sideList" :key="i.name"><span>{{i.name}}</span><b :class="{bad:i.bad}">{{i.status}}</b></p></div>
    <div class="hint">IOT 场景已移除机器人路线，支持楼栋下钻、点位弹窗、视角飞行、告警联动和缩放限制。</div>
  </div>
</template>

<script>
import * as THREE from 'three'
import { OrbitControls } from 'three/examples/jsm/controls/OrbitControls.js'
import { CSS2DObject, CSS2DRenderer } from 'three/examples/jsm/renderers/CSS2DRenderer.js'

export default {
  name: 'IotCenterScene',
  props: { height: { type: String, default: '620px' } },
  data () { return { floorMode:false, floorTitle:'1号楼 · 3F 楼层内部', loading:false, loadingText:'正在下钻到楼层内部...', tip:{show:false,x:0,y:0,title:'',type:'',location:'',status:'',desc:'',alarm:false}, sideList:[{name:'1号设备房',status:'正常'},{name:'水泵房',status:'液位偏高',bad:true},{name:'配电房',status:'温度偏高',bad:true},{name:'消防通道',status:'在线'}] } },
  mounted(){ this.init(); this.buildPark(); this.loop(); window.addEventListener('resize',this.resize) },
  beforeDestroy(){ cancelAnimationFrame(this.raf); window.removeEventListener('resize',this.resize); this.renderer&&this.renderer.dispose(); this.$refs.host.innerHTML='' },
  methods:{
    init(){
      this.scene=new THREE.Scene(); this.scene.fog=new THREE.Fog(0x020811,100,310); this.camera=new THREE.PerspectiveCamera(45,1,.1,1500); this.camera.position.set(96,72,108);
      this.renderer=new THREE.WebGLRenderer({antialias:true,alpha:false}); this.renderer.setPixelRatio(Math.min(devicePixelRatio||1,2)); this.renderer.setClearColor(0x020811,1); this.renderer.outputColorSpace=THREE.SRGBColorSpace; this.$refs.host.appendChild(this.renderer.domElement);
      this.labels=new CSS2DRenderer(); this.labels.domElement.style.cssText='position:absolute;left:0;top:0;pointer-events:none'; this.$refs.host.appendChild(this.labels.domElement);
      this.controls=new OrbitControls(this.camera,this.renderer.domElement); this.controls.enableDamping=true; this.controls.dampingFactor=.08; this.controls.target.set(0,0,0); this.controls.minDistance=36; this.controls.maxDistance=180; this.controls.maxPolarAngle=Math.PI/2.08; this.controls.screenSpacePanning=false;
      this.raycaster=new THREE.Raycaster(); this.pointer=new THREE.Vector2(); this.clicks=[]; this.anims=[]; this.devices={}; this.park=new THREE.Group(); this.floor=new THREE.Group(); this.scene.add(this.park,this.floor);
      this.scene.add(new THREE.AmbientLight(0x9eefff,.8)); const d=new THREE.DirectionalLight(0xffffff,1.35); d.position.set(80,140,80); this.scene.add(d); const p=new THREE.PointLight(0x00f5ff,4.5,180); p.position.set(0,58,0); this.scene.add(p); this.resize(); this.renderer.domElement.addEventListener('pointerdown',this.pick)
    },
    resize(){ if(!this.renderer)return; const w=this.$refs.host.clientWidth||1,h=this.$refs.host.clientHeight||1; this.camera.aspect=w/h; this.camera.updateProjectionMatrix(); this.renderer.setSize(w,h); this.labels.setSize(w,h) },
    clear(g){ while(g.children.length)g.remove(g.children[0]) },
    mat(c,o=.78,e=0x00384c){ return new THREE.MeshStandardMaterial({color:c,transparent:true,opacity:o,roughness:.46,metalness:.24,emissive:e,emissiveIntensity:.55}) },
    edges(m,c=0x00eaff,o=.7){ m.add(new THREE.LineSegments(new THREE.EdgesGeometry(m.geometry),new THREE.LineBasicMaterial({color:c,transparent:true,opacity:o}))) },
    label(t,bad){ const el=document.createElement('div'); el.textContent=t; el.style.cssText=`color:#eaffff;font-size:13px;white-space:nowrap;background:${bad?'rgba(70,18,20,.88)':'rgba(1,26,36,.82)'};border:1px solid ${bad?'rgba(255,85,79,.75)':'rgba(0,245,255,.62)'};padding:5px 10px;box-shadow:0 0 14px rgba(0,245,255,.3);pointer-events:none`; return new CSS2DObject(el) },
    ring(x,z,r,c=0x00f5ff){ const g=new THREE.Group(); g.position.set(x,.12,z); const a=new THREE.Mesh(new THREE.RingGeometry(r*.64,r,64),new THREE.MeshBasicMaterial({color:c,transparent:true,opacity:.24,side:THREE.DoubleSide})); a.rotation.x=-Math.PI/2; const b=new THREE.Mesh(new THREE.RingGeometry(r*.24,r*.38,64),new THREE.MeshBasicMaterial({color:c,transparent:true,opacity:.34,side:THREE.DoubleSide})); b.rotation.x=-Math.PI/2; g.add(a,b); this.anims.push(t=>{a.rotation.z=t*.55;b.rotation.z=-t*.8}); return g },
    addClick(o,p){ o.userData.payload=p; this.clicks.push(o) },
    buildPark(){ this.floorMode=false; this.tip.show=false; this.clicks=[]; this.anims=[]; this.devices={}; this.clear(this.park); this.clear(this.floor); this.park.visible=true; this.floor.visible=false; this.controls.minDistance=42; this.controls.maxDistance=190;
      const grid=new THREE.GridHelper(210,54,0x00ffff,0x0b4050); grid.material.transparent=true; grid.material.opacity=.23; this.park.add(grid); const ground=new THREE.Mesh(new THREE.PlaneGeometry(220,220),this.mat(0x071520,.96,0x000000)); ground.rotation.x=-Math.PI/2; this.park.add(ground);
      [[0,8,172,12],[36,-10,12,128],[-46,25,84,9],[64,40,58,9]].forEach(r=>{const m=new THREE.Mesh(new THREE.PlaneGeometry(r[2],r[3]),new THREE.MeshBasicMaterial({color:0x00f5ff,transparent:true,opacity:.16,side:THREE.DoubleSide}));m.rotation.x=-Math.PI/2;m.position.set(r[0],.1,r[1]);this.park.add(m)});
      const bs=[['b1','1号楼',-50,-22,36,25,28,'正常'],['b2','2号楼',0,-30,38,34,26,'正常'],['b3','设备房',-74,34,24,15,18,'正常'],['b4','配电房',44,-12,32,24,24,'温度偏高',true],['b5','充电区',75,34,34,18,20,'异常待处理',true]];
      bs.forEach(b=>{const g=new THREE.Group(); g.position.set(b[2],0,b[3]); const body=new THREE.Mesh(new THREE.BoxGeometry(b[4],b[5],b[6]),this.mat(b[8]?0x351719:0x0c4d67,.78,b[8]?0x401010:0x00384c)); body.position.y=b[5]/2; this.edges(body,b[8]?0xff554f:0x00eaff,.76); g.add(body); for(let i=1;i<=4;i++){const f=new THREE.Mesh(new THREE.BoxGeometry(b[4]+.4,.22,b[6]+.4),new THREE.MeshBasicMaterial({color:0x00f5ff,transparent:true,opacity:.1}));f.position.y=b[5]/5*i;g.add(f)} const lab=this.label(b[1],b[8]); lab.position.set(0,b[5]+9,0); g.add(lab); this.park.add(this.ring(b[2],b[3],b[8]?11:9,b[8]?0xff554f:0x00f5ff)); this.addClick(g,{id:b[0],title:b[1],type:'楼栋 / 区域',location:'智慧物业园区',status:b[7],alarm:!!b[8],desc:'点击后切换到楼层内部视角，展示摄像头、门禁、消防、环境点位。',camera:[[b[2]+38,38,b[3]+44],[b[2],8,b[3]]],action:()=>this.drill(b)}); this.park.add(g)});
      [['cam','AI摄像头',-58,30,-18,'消防通道','在线','◉'],['smoke','烟感',-46,31,-28,'1号楼','正常','♨'],['door','门禁',-76,20,34,'设备房','在线','▣'],['water','液位',-20,15,22,'水泵房','液位偏高','◍',true],['temp','温度',42,31,-10,'配电房','温度偏高','♨',true],['elevator','电梯厅摄像头',2,40,-30,'2号楼电梯厅','在线','◉'],['charger','充电区监测',75,24,34,'充电区','异常待处理','⚡',true],['fire','消防栓压力',18,12,42,'主干道','正常','◆']].forEach(d=>this.marker(this.park,{id:d[0],title:d[1],pos:[d[2],d[3],d[4]],location:d[5],status:d[6],icon:d[7],alarm:d[8],type:d[1]}));
      this.fly([96,72,108],[0,4,0])
    },
    drill(b){ this.$emit('scene-event',{type:'drill-down',title:b[1]}); this.loadingText='正在下钻到'+b[1]+'楼层内部...'; this.loading=true; this.floorTitle=b[1]+' · 楼层内部'; this.fly([b[2]+26,28,b[3]+32],[b[2],8,b[3]],.055); setTimeout(()=>{this.buildFloor();this.loading=false},760) },
    buildFloor(){ this.floorMode=true; this.tip.show=false; this.clicks=[]; this.anims=[]; this.devices={}; this.clear(this.park); this.clear(this.floor); this.park.visible=false; this.floor.visible=true; this.controls.minDistance=28; this.controls.maxDistance=125;
      const grid=new THREE.GridHelper(145,36,0x00ffff,0x123d4b); grid.material.transparent=true; grid.material.opacity=.18; this.floor.add(grid); const base=new THREE.Mesh(new THREE.PlaneGeometry(150,96),this.mat(0x071520,.98,0)); base.rotation.x=-Math.PI/2; this.floor.add(base);
      [['公共走廊',18,-2,94,18,0x00f5ff,false],['大堂',-48,-22,36,28,0x0ba7b8,false],['电梯厅',-4,-24,28,26,0x0f5f8d,false],['水泵房',48,-26,28,24,0xff554f,true],['配电房',-42,26,36,24,0xffb642,true],['设备间',8,26,32,24,0x00f5ff,false],['监控室',50,24,28,24,0x2d8cff,false]].forEach(r=>{const g=new THREE.Group(); const pl=new THREE.Mesh(new THREE.PlaneGeometry(r[3],r[4]),new THREE.MeshBasicMaterial({color:r[5],transparent:true,opacity:r[6]?.2:.18,side:THREE.DoubleSide})); pl.rotation.x=-Math.PI/2; pl.position.set(r[1],.2,r[2]); const bd=new THREE.LineSegments(new THREE.EdgesGeometry(new THREE.BoxGeometry(r[3],.18,r[4])),new THREE.LineBasicMaterial({color:r[5],transparent:true,opacity:.72})); bd.position.set(r[1],.34,r[2]); g.add(pl,bd); const lab=this.label(r[0],r[6]); lab.position.set(r[1],5.4,r[2]); this.floor.add(lab); this.addClick(g,{title:r[0],type:'楼层房间 / 区域',location:this.floorTitle,status:r[6]?'存在异常':'正常',alarm:r[6],desc:'楼层内部区域，可查看房间设备点位、告警、视频与工单。',camera:[[r[1]+18,34,r[2]+22],[r[1],0,r[2]]]}); this.floor.add(g)});
      [[-74,0,1,92],[74,0,1,92],[0,-47,148,1],[0,47,148,1],[18,-14,94,1],[18,14,94,1],[-24,0,1,46],[32,0,1,48]].forEach(w=>{const m=new THREE.Mesh(new THREE.BoxGeometry(w[2],5.6,w[3]),this.mat(0x244b5a,.34,0x002b34));m.position.set(w[0],2.8,w[1]);this.floor.add(m)});
      [['f-cam1','走廊摄像头','AI摄像头','◉',-14,8,-2,'公共走廊','在线'],['f-cam2','大堂摄像头','AI摄像头','◉',-48,8,-22,'大堂','在线'],['f-smoke','烟感-水泵房','烟感','♨',48,8,-26,'水泵房','正常'],['f-water','液位-水泵房','液位','◍',58,8,-22,'水泵房','液位偏高',true],['f-temp','温度-配电房','温度','♨',-42,8,26,'配电房','温度偏高',true],['f-door','门禁-设备间','门禁','▣',8,7,14,'设备间','在线'],['f-elevator','电梯状态点位','电梯','▤',-4,7,-24,'电梯厅','正常'],['f-fire','消防栓压力','消防','◆',18,7,8,'公共走廊','正常']].forEach(d=>this.marker(this.floor,{id:d[0],title:d[1],type:d[2],icon:d[3],pos:[d[4],d[5],d[6]],location:d[7],status:d[8],alarm:d[9]}));
      this.sideList=[{name:'公共走廊摄像头',status:'在线'},{name:'水泵房液位',status:'液位偏高',bad:true},{name:'配电房温度',status:'温度偏高',bad:true},{name:'消防烟感',status:'正常'}]; this.fly([0,88,34],[0,0,0],.055)
    },
    marker(group,d){ const m=new THREE.Group(); m.position.set(...d.pos); const c=d.alarm?0xff554f:0x00f5ff; const pole=new THREE.Mesh(new THREE.CylinderGeometry(.18,.18,Math.max(d.pos[1]-.5,2),12),new THREE.MeshBasicMaterial({color:c,transparent:true,opacity:.55})); pole.position.y=-d.pos[1]/2; const ball=new THREE.Mesh(new THREE.SphereGeometry(2.5,32,16),new THREE.MeshStandardMaterial({color:c,emissive:c,emissiveIntensity:d.alarm?1.7:1.05,transparent:true,opacity:.92})); const ring=new THREE.Mesh(new THREE.RingGeometry(3.6,5.4,40),new THREE.MeshBasicMaterial({color:c,transparent:true,opacity:.42,side:THREE.DoubleSide})); ring.rotation.x=-Math.PI/2; ring.position.y=-d.pos[1]+.25; const lab=this.label((d.icon||'●')+' '+d.title,d.alarm); lab.position.set(0,6.2,0); m.add(pole,ball,ring,lab); this.addClick(m,{...d,desc:d.alarm?'设备异常，支持联动视频、派单、复位与趋势查看。':'设备在线，运行状态正常。',camera:[[d.pos[0]+20,d.pos[1]+20,d.pos[2]+22],d.pos]}); group.add(m); this.devices[d.id]=m; this.anims.push(t=>{ball.scale.setScalar(1+Math.sin(t*(d.alarm?7:3))*(d.alarm?.22:.08)); ring.rotation.z+=d.alarm?.035:.018}) },
    backPark(){ if(!this.floorMode){this.fly([96,72,108],[0,4,0]);return} this.loadingText='正在返回园区总览...'; this.loading=true; setTimeout(()=>{this.buildPark();this.loading=false;this.sideList=[{name:'1号设备房',status:'正常'},{name:'水泵房',status:'液位偏高',bad:true},{name:'配电房',status:'温度偏高',bad:true},{name:'消防通道',status:'在线'}]},520) },
    view(v){ const p=this.floorMode?{fire:[[58,42,10],[48,0,-26]],security:[[-22,38,20],[-14,0,-2]],room:[[-24,40,48],[-42,0,26]]}:{fire:[[-35,44,10],[-52,8,-20]],security:[[-84,42,30],[-74,8,34]],room:[[-34,38,54],[-20,6,22]]}; if(p[v])this.fly(p[v][0],p[v][1]) },
    alarm(){ const key=this.floorMode?'f-water':'charger'; const o=this.devices[key]||Object.values(this.devices)[0]; if(!o)return; const w=new THREE.Vector3(); o.getWorldPosition(w); this.fly([w.x+22,w.y+30,w.z+25],[w.x,w.y,w.z],.06); this.$emit('scene-event',{type:'alarm',title:'模拟设备告警'}); const s=new THREE.Mesh(new THREE.SphereGeometry(10,32,16),new THREE.MeshBasicMaterial({color:0xff554f,transparent:true,opacity:.22,wireframe:true})); s.position.copy(w); this.scene.add(s); const st=performance.now(); const fn=t=>{s.scale.setScalar(1+Math.sin(t*7)*.22); if(performance.now()-st>9000){this.scene.remove(s);this.anims=this.anims.filter(a=>a!==fn)}}; this.anims.push(fn) },
    pick(e){ const r=this.renderer.domElement.getBoundingClientRect(); this.pointer.x=((e.clientX-r.left)/r.width)*2-1; this.pointer.y=-((e.clientY-r.top)/r.height)*2+1; this.raycaster.setFromCamera(this.pointer,this.camera); const hits=this.raycaster.intersectObjects(this.clicks,true); if(!hits.length){this.tip.show=false;return} let o=hits[0].object; while(o&&!o.userData.payload)o=o.parent; if(!o)return; const p=o.userData.payload; if(p.camera)this.fly(p.camera[0],p.camera[1],.06); this.tip={show:true,x:e.clientX-r.left,y:e.clientY-r.top,title:p.title,type:p.type,location:p.location,status:p.status,desc:p.desc,alarm:!!p.alarm}; this.$emit('scene-event',{type:'select',title:p.title,payload:p}); if(p.action)setTimeout(p.action,360) },
    fly(p,t,s=.045){ this.targetCam=new THREE.Vector3(...p); this.targetTar=new THREE.Vector3(...t); this.speed=s },
    updateFly(){ if(!this.targetCam)return; this.camera.position.lerp(this.targetCam,this.speed); this.controls.target.lerp(this.targetTar,this.speed*1.25); if(this.camera.position.distanceTo(this.targetCam)<.35)this.targetCam=null },
    clamp(){ this.camera.position.y=Math.max(this.camera.position.y,8); const d=this.camera.position.distanceTo(this.controls.target); if(d>this.controls.maxDistance+4){const dir=this.camera.position.clone().sub(this.controls.target).normalize();this.camera.position.copy(this.controls.target.clone().add(dir.multiplyScalar(this.controls.maxDistance)))} },
    loop(){ this.raf=requestAnimationFrame(this.loop); const t=performance.now()/1000; this.controls.update(); this.updateFly(); this.clamp(); this.anims.forEach(fn=>fn(t)); this.renderer.render(this.scene,this.camera); this.labels.render(this.scene,this.camera) }
  }
}
</script>

<style scoped>
.scene-panel{position:relative;width:100%;min-height:520px;overflow:hidden;border:1px solid rgba(0,245,255,.46);background:#020811;box-shadow:inset 0 0 30px rgba(0,245,255,.08)}.scene-panel:before{content:"";position:absolute;inset:0;pointer-events:none;background:repeating-linear-gradient(90deg,transparent 0 38px,rgba(0,245,255,.035) 39px 40px),repeating-linear-gradient(0deg,transparent 0 38px,rgba(0,245,255,.03) 39px 40px);z-index:2}.head{position:absolute;left:18px;right:18px;top:14px;z-index:8;display:flex;justify-content:space-between;pointer-events:none}.head b{font-size:22px;letter-spacing:3px;text-shadow:0 0 10px #00f5ff}.head span{color:rgba(210,250,255,.58);font-size:13px}.toolbar{position:absolute;left:24px;top:62px;z-index:8;display:flex;gap:8px}.toolbar button{height:30px;padding:0 12px;color:#dff;border:1px solid rgba(0,245,255,.48);background:rgba(0,35,50,.78);cursor:pointer}.toolbar .danger{border-color:rgba(255,85,79,.72);background:rgba(82,18,22,.72)}.host{position:absolute;inset:0;z-index:1;background:#020811}.tip{position:absolute;z-index:12;min-width:230px;transform:translate(-50%,-112%);padding:12px;border:1px solid rgba(0,245,255,.66);background:rgba(1,22,32,.92);box-shadow:0 0 22px rgba(0,245,255,.22);pointer-events:none}.tip.alarm{border-color:rgba(255,85,79,.78)}.tip h4{margin:0 0 8px;color:#00f5ff}.tip p{margin:5px 0;color:#cfe9ee;font-size:13px}.tip em{color:#ff6c66;font-style:normal}.tip small{color:rgba(220,255,255,.65)}.side{position:absolute;right:18px;bottom:44px;z-index:8;width:248px;padding:12px;border:1px solid rgba(0,245,255,.36);background:rgba(0,22,34,.76)}.side h4{margin:0 0 8px}.side p{display:flex;justify-content:space-between;border-bottom:1px solid rgba(0,245,255,.1);padding:6px 0;margin:0;font-size:13px}.side b{color:#26f2a3}.side b.bad{color:#ff6c66}.hint{position:absolute;left:18px;bottom:14px;z-index:8;color:rgba(220,255,255,.48);font-size:12px}.mask{position:absolute;inset:0;z-index:20;display:grid;place-items:center;background:rgba(0,5,10,.35);backdrop-filter:blur(1px);font-size:18px;letter-spacing:3px;text-shadow:0 0 12px #00f5ff}.fade-enter-active,.fade-leave-active{transition:opacity .28s}.fade-enter,.fade-leave-to{opacity:0}
</style>
